<?php

# Migración para la tabla `miembros`

return [
	"CREATE TABLE IF NOT EXISTS `" . $prefix . "miembros` (\n"
		."  `user_id` int(11) NOT NULL AUTO_INCREMENT,\n"
		."  `user_activo` int(1) NOT NULL DEFAULT 0,\n"
		."  `user_amigos` int(11) NOT NULL DEFAULT 0,\n"
		."  `user_bad_hits` int(2) unsigned NOT NULL DEFAULT 0,\n"
		."  `user_baneado` int(1) NOT NULL DEFAULT 0,\n"
		."  `user_cache` int(10) NOT NULL DEFAULT 0,\n"
		."  `user_comentarios` int(11) NOT NULL DEFAULT 0,\n"
		."  `user_email` varchar(80) NOT NULL DEFAULT '',\n"
		."  `user_verificado` int(1) NOT NULL DEFAULT 0,\n"
		."  `user_chat` int(12) NOT NULL DEFAULT 0,\n"
		."  `user_secret_2fa` text NULL,\n"
		."  `user_recovery` text NULL,\n"
		."  `user_last_ip` varchar(38) NOT NULL DEFAULT 0,\n"
		."  `user_lastactive` int(10) NOT NULL DEFAULT 0,\n"
		."  `user_lastlogin` int(10) NOT NULL DEFAULT 0,\n"
		."  `user_lastpost` int(10) NOT NULL DEFAULT 0,\n"
		."  `user_name_changes` int(11) NOT NULL DEFAULT 3,\n"
		."  `user_name` varchar(24) NOT NULL DEFAULT '',\n"
		."  `user_nextpuntos` int(10) NOT NULL DEFAULT 0,\n"
		."  `user_password` varchar(66) NOT NULL DEFAULT '',\n"
		."  `user_posts` int(11) NOT NULL DEFAULT 0,\n"
		."  `user_puntos` int(6) unsigned NOT NULL DEFAULT 0,\n"
		."  `user_puntosxdar` int(2) unsigned NOT NULL DEFAULT 0,\n"
		."  `user_rango` int(3) NOT NULL DEFAULT 3,\n"
		."  `user_registro` int(10) NOT NULL DEFAULT 0,\n"
		."  `user_outtime_type` int(1) NOT NULL DEFAULT 0,\n"
		."  `user_outtime_start` int(10) NOT NULL DEFAULT 0,\n"
		."  `user_outtime` int(10) NOT NULL DEFAULT 0,\n"
		."  `user_seguidores` bigint NOT NULL DEFAULT 0,\n"
		."  `user_seguidos` bigint NOT NULL DEFAULT 0,\n"
		."  PRIMARY KEY (`user_id`)\n"
		.") ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci AUTO_INCREMENT=1 ;"
];
