<?php

# Migración para la tabla `configuracion`

return [
	"CREATE TABLE IF NOT EXISTS `" . $prefix . "configuracion` (\n"
		."  `tscript_id` int(11) NOT NULL DEFAULT 0,\n"
		."  `titulo` varchar(30) NOT NULL DEFAULT '',\n"
		."  `slogan` varchar(32) NOT NULL DEFAULT '',\n"
		."  `url` tinytext NULL,\n"
		."  `email` varchar(80) NOT NULL DEFAULT '',\n"
		."  `banner` varchar(100) NOT NULL DEFAULT '',\n"
		."  `tema` varchar(30) NOT NULL DEFAULT 'default',\n"
		."  `update_id` varchar(20) NOT NULL DEFAULT '',\n"
		."  `c_allow_ticket` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_allow_foro` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_allow_fuentes` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_ver_vistas_global` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_quitar_vistas_global` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_visitas_tiempo` int(2) NOT NULL DEFAULT 5,\n"
		."  `c_avatar` int(1) NOT NULL DEFAULT 0,\n"
		."  `leaving` int(1) NOT NULL DEFAULT 0,\n"
		."  `ads_300` text NULL,\n"
		."  `ads_468` text NULL,\n"
		."  `ads_160` text NULL,\n"
		."  `ads_728` text NULL,\n"
		."  `ads_search` varchar(50) NOT NULL DEFAULT '',\n"
		."  `c_last_active` int(2) NOT NULL DEFAULT 15,\n"
		."  `c_allow_sess_ip` int(1) NOT NULL DEFAULT 1,\n"
		."  `c_count_guests` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_reg_active` int(1) NOT NULL DEFAULT 1,\n"
		."  `c_reg_activate` int(1) NOT NULL DEFAULT 1,\n"
		."  `c_reg_rango` int(5) NOT NULL DEFAULT 3,\n"
		."  `c_met_welcome` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_message_welcome` varchar(500) NOT NULL DEFAULT 'Hola [usuario], [welcome] a [b][web][/b].',\n"
		."  `c_fotos_private` int(11) NOT NULL DEFAULT 0,\n"
		."  `c_hits_guest` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_keep_points` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_allow_points` int(11) NOT NULL DEFAULT 0,\n"
		."  `c_allow_edad` int(11) NOT NULL DEFAULT 16,\n"
		."  `c_max_posts` int(2) NOT NULL DEFAULT 17,\n"
		."  `c_max_com` int(3) NOT NULL DEFAULT 50,\n"
		."  `c_max_nots` int(3) NOT NULL DEFAULT 99,\n"
		."  `c_max_acts` int(3) NOT NULL DEFAULT 99,\n"
		."  `c_newr_type` int(11) NOT NULL DEFAULT 0,\n"
		."  `c_allow_sump` int(11) NOT NULL DEFAULT 0,\n"
		."  `c_allow_firma` int(1) NOT NULL DEFAULT 1,\n"
		."  `c_allow_upload` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_allow_portal` int(1) NOT NULL DEFAULT 1,\n"
		."  `c_allow_live` int(1) NOT NULL DEFAULT 1,\n"
		."  `c_see_mod` int(1) NOT NULL DEFAULT 0,\n"
		."  `c_stats_cache` int(7) NOT NULL DEFAULT 15,\n"
		."  `c_desapprove_post` int(1) NOT NULL DEFAULT 0,\n"
		."  `offline` int(1) NOT NULL DEFAULT 0,\n"
		."  `offline_message` varchar(255) NOT NULL DEFAULT 'Estamos en mantenimiento',\n"
		."  `pkey` varchar(55) NOT NULL DEFAULT '',\n"
		."  `skey` varchar(55) NOT NULL DEFAULT '',\n"
		."  `version` varchar(30) NOT NULL DEFAULT '',\n"
		."  `version_code` varchar(30) NOT NULL DEFAULT '',\n"
		."  PRIMARY KEY (`tscript_id`)\n"
		.") ENGINE=MyISAM DEFAULT CHARSET=utf8;"
];
